trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  email_destinatario: 'janison6@gmail.com' # Substitua pelo seu email de teste
  smtp_server: 'smtp.gmail.com' # Substitua pelo seu servidor SMTP ou pelo servidor do Mailtrap

stages:
- stage: TestEmail
  displayName: 'Testar Envio de Email'
  jobs:
  - job: SendEmail
    steps:
    - script: |
        echo "Enviando email de teste..."
        echo "Subject: Teste de Email do Pipeline" | mail -s "Teste de Email" $(email_destinatario) -S $(smtp_server)
      displayName: 'Enviar Email'